### ISSUE TITLE
request for the dataset

### ISSUE THREAD

**Issue by storageincharge** [sshh12/venmo-research#1]
Hi there:

Open this issue for requesting the dataset.  Used for research and science purpose.  Thank you!

**Comment by sshh12** [comment]
Haha, that was fast. Go ahead and send me an email (`shrivu.shankar (at) utexas.edu`) with your name, organization/affiliation, description of the project/intended dataset use. I'll need then need to verify w/@F1356AK and then we can figured out the best way to transfer it (~21GB compressed). 

edit: Just realized this was posted over a month ago, sorry for the delay!
